koishijs/koishi-plugin-booru

packages/danbooru/src/index.ts
packages/gelbooru/src/index.ts
packages/konachan/src/index.ts
packages/lolibooru/src/index.ts
packages/lolicon/src/index.ts
packages/pixiv/src/index.ts
packages/safebooru/src/index.ts
packages/yande/src/index.ts

Increase the minimum value of option(weight) to disallow negative numbers
fix issue ([#16](https://github.com/koishijs/koishi-plugin-booru/issues/16))
fix #16

fix: add minimum value to option(weight)

---

packages/danbooru/src/index.ts
packages/gelbooru/src/index.ts
packages/konachan/src/index.ts
packages/lolibooru/src/index.ts
packages/lolicon/src/index.ts
packages/pixiv/src/index.ts
packages/safebooru/src/index.ts
packages/yande/src/index.ts

refactor: clarify config

---

packages/sankaku/package.json
packages/sankaku/src/index.ts
packages/sankaku/src/types.ts
packages/sankaku/tsconfig.json

feat: add sankaku complex support

---

packages/core/src/index.ts

fix(core): file name uppercase

---

packages/core/src/index.ts
packages/core/src/locales/zh-CN.yml

feat: add no source notify

---

docs/zh-CN/plugins/e621.md
packages/e621/package.json
packages/e621/readme.md
packages/e621/src/index.ts
packages/e621/src/types.ts
packages/e621/tsconfig.json

Add source support of  [`e621.net`](e621.net) and [`e926.net`](e926.net).
close #91

feat: support source e621

---

packages/lolibooru/src/index.ts

fix(lolibooru): URL white spaces not transformed

---

packages/core/src/index.tsx

fix: caller is deprecated in current Koishi

---

packages/pixiv/package.json
packages/pixiv/src/index.ts

feat: add multiple bypass pixiv referer validation methods

---

packages/core/src/command.tsx

refa: update the standard image element to `<img>`

---

packages/pixiv/package.json
packages/pixiv/src/index.ts

feat(pixiv): shuffle results before return

---

.github/ISSUE_TEMPLATE/feature.yml
.github/ISSUE_TEMPLATE/new-source.yml

instead of use the same form with feature request

chore: add new source form for issue template

---

packages/core/src/command.tsx

fix: options after query not be passed

---

docs/zh-CN/develop/api.md
packages/core/src/index.ts

fix: migrate obsolete usages for Koishi v4.17

---

packages/core/package.json
packages/danbooru/package.json
packages/e621/package.json
packages/gelbooru/package.json
packages/konachan/package.json
packages/local/package.json
packages/lolibooru/package.json
packages/lolicon/package.json
packages/moehu/package.json
packages/pixiv/package.json
packages/safebooru/package.json
packages/sankaku/package.json
packages/yande/package.json

chore: bump version to 1.2.0

---

packages/core/package.json

chore: bump version to 1.2.1

---

.github/labeler.yml
.github/workflows/labeler.yml

ref: https://github.com/actions/labeler

ci: add labeler for pull requests

---

packages/pixiv/package.json
packages/pixiv/src/index.ts

feat(pixiv): migrate arraybuffer to stream again

---

packages/core/package.json
packages/danbooru/package.json
packages/e621/package.json
packages/gelbooru/package.json
packages/konachan/package.json
packages/local/package.json
packages/lolibooru/package.json
packages/lolicon/package.json
packages/moehu/package.json
packages/pixiv/package.json
packages/safebooru/package.json
packages/sankaku/package.json
packages/yande/package.json

Ref: https://docs.npmjs.com/generating-provenance-statements
Although

chore: add publish provenance

---

packages/core/package.json

chore: bump dependencies

---

packages/core/src/command.tsx

fix: set default image count to 1

---

packages/danbooru/src/index.ts
packages/e621/src/index.ts
packages/gelbooru/src/index.ts
packages/konachan/src/index.ts
packages/lolibooru/src/index.ts
packages/lolicon/src/index.ts
packages/moehu/src/index.ts
packages/pixiv/src/index.ts
packages/safebooru/src/index.ts
packages/sankaku/src/index.ts
packages/yande/src/index.ts

feat: make most source plugin reusable
